package com.example.houshuai.qingdan.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shouchangDaoConfig;
    private final WenZhangDao shouchangDao;

    private final DaoConfig mShangPinDaoConfig;
    private final ShangPinDao mShangPinDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shouchangDaoConfig = daoConfigMap.get(WenZhangDao.class).clone();
        shouchangDaoConfig.initIdentityScope(type);

        mShangPinDaoConfig = daoConfigMap.get(ShangPinDao.class).clone();
        mShangPinDaoConfig.initIdentityScope(type);

        shouchangDao = new WenZhangDao(shouchangDaoConfig, this);
        mShangPinDao = new ShangPinDao(mShangPinDaoConfig, this);

        registerDao(WenZhang.class, shouchangDao);
        registerDao(ShangPin.class, mShangPinDao);
    }

    public void clear() {
        shouchangDaoConfig.getIdentityScope().clear();
    }

    public void mclear() {
        mShangPinDaoConfig.getIdentityScope().clear();
    }

    public WenZhangDao getShouchangDao() {
        return shouchangDao;
    }

    public ShangPinDao getShangPinDAo() {
        return mShangPinDao;
    }

}
