package com.example.houshuai.qingdan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOUCHANG.
 */
public class WenZhang {

    private Long id;
    /** Not-null value. */
    private String url;
    private String title;
    private String content;
    private String image;
    private String addLove;
    private String addSee;
    private java.util.Date date;

    public WenZhang() {
    }

    public WenZhang(Long id) {
        this.id = id;
    }

    public WenZhang(Long id, String url, String title, String content, String image, String addLove, String addSee, java.util.Date date) {
        this.id = id;
        this.url = url;
        this.title = title;
        this.content = content;
        this.image = image;
        this.addLove = addLove;
        this.addSee = addSee;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getAddLove() {
        return addLove;
    }

    public void setAddLove(String addLove) {
        this.addLove = addLove;
    }

    public String getAddSee() {
        return addSee;
    }

    public void setAddSee(String addSee) {
        this.addSee = addSee;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    @Override
    public String toString() {
        return "WenZhang{" +
                "id=" + id +
                ", url='" + url + '\'' +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", image='" + image + '\'' +
                ", addLove='" + addLove + '\'' +
                ", addSee='" + addSee + '\'' +
                ", date=" + date +
                '}';
    }
}
